apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "application.Fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: catapp
    component: mesh
spec:
  selector:
    matchLabels:
      name: {{ .Values.Release }}
  template:
    metadata:
      labels:
        app: catapp
        component: mesh
    spec:
      containers:
      - name: meshcat
        image: busybox
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers